"""Where each state's government stands on whether Israel's conduct in Gaza is genocide.

Read by build_positions.py, which joins every entry to the map and to the list
of UN member states and writes the result into data/world-positions.json.

The base is the Wikipedia article "Gaza genocide recognition" (revision
1376504299), which cites a statement for each state; every entry here carries
that statement's own source rather than the article. The article was then
corrected where the record has moved since it was written: five governments
that once used the word have been replaced by governments that have reversed
the policy, and the statements made at the 81st General Assembly this week are
added.

A position is what the state's government has said, in the words of its head
of state or government, its foreign minister or foreign ministry, another
cabinet minister (named as such), an official government publication, or a
formal legal act. Parliaments, parties, opposition figures and diplomats
speaking for themselves are not counted.

  says      the government has itself described the conduct as genocide
  joint     the government's only statement using the word is a joint one,
            the declaration of 31 Arab and Islamic states of 15 August 2025
  reversed  a previous government said it; the government now in office has
            moved the other way and has not repeated it
  defers    the government says it is for a court to decide
  unclear   the government has said something that is neither
  rejects   the government has said it is not genocide, or has cast doubt on
            the word, or has filed at the ICJ against the characterisation

Every state not listed has no statement either way on the record this
research found. That is not the same as having none, and the page says so.
A state keeps the strongest statement its governments have made unless a later
government has reversed it; where the speaker has since left office the entry
says so.
"""

JOINT_2025 = {
    "who": "Joint statement of 31 Arab and Islamic states, the Arab League, the OIC and the GCC",
    "role": "Foreign ministers",
    "date": "2025-08-15",
    "quote": "reiterate their rejection and condemnation of the crimes of Israeli aggression, genocide, and ethnic cleansing",
    "source": "https://mofa.gov.qa/en/latest-articles/statements/31-arab--islamic-countries--arab-league--oic--gcc-condemn-so-called--greater-israel-vision",
    "outlet": "Qatar Ministry of Foreign Affairs",
}

# The 31 signatories, as named in the statement.
JOINT_2025_SIGNATORIES = [
    "Qatar", "Jordan", "Algeria", "Bahrain", "Bangladesh", "Chad", "Comoros", "Djibouti", "Egypt",
    "Gambia", "Indonesia", "Iraq", "Kuwait", "Lebanon", "Libya", "Maldives", "Mauritania", "Morocco",
    "Nigeria", "Oman", "Pakistan", "Palestine", "Saudi Arabia", "Senegal", "Sierra Leone", "Somalia",
    "Sudan", "Syria", "Turkey", "United Arab Emirates", "Yemen",
]

UNGA81 = "https://www.middleeasteye.net/news/un-general-assembly-2026-war-iran-and-gaza-genocide-dominate"

POSITIONS = [
    # ------------------------------------------------------------------ says
    {"name": "South Africa", "position": "says", "who": "Government of South Africa", "role": "Applicant",
     "date": "2023-12-29", "summary": "Brought the case alleging genocide at the International Court of Justice, "
     "after the Minister in the Presidency, Khumbudzo Ntshavheni, condemned “the atrocities and genocide of the "
     "Israeli government” on 6 November 2023.",
     "source": "https://www.icj-cij.org/case/192", "outlet": "International Court of Justice"},
    {"name": "Afghanistan", "position": "says", "who": "Ministry of Foreign Affairs", "role": "Taliban authorities",
     "date": "2023-10-18", "quote": "calling for the immediate end of the ongoing genocide",
     "source": "https://mfa.gov.af/en/the-ministry-of-foreign-affairs-of-the-islamic-emirate-of-afghanistan-condemns-in-the-strongest-terms-the-bombardment-of-the-al-mamadani-hospital-in-gaza-by-the-zionist-forces-and-deems-this-act-barba/",
     "outlet": "Afghan Ministry of Foreign Affairs",
     "note": "The Taliban authorities are not recognised by the United Nations as the government of Afghanistan."},
    {"name": "Algeria", "position": "says", "who": "Abdelmadjid Tebboune", "role": "President", "date": "2023-11-07",
     "quote": "Where is the global conscience that has become absent regarding the genocide being committed?",
     "source": "https://www.middleeastmonitor.com/20231107-algeria-calls-on-icc-to-hold-israel-accountable-for-its-crimes-in-gaza/",
     "outlet": "Middle East Monitor"},
    {"name": "Angola", "position": "says", "who": "João Lourenço", "role": "President", "date": "2024-09-24",
     "quote": "everything it can to prevent the genocide that the world is witnessing live in the Gaza Strip",
     "source": "https://gadebate.un.org/sites/default/files/gastatements/79/ao_en.pdf", "outlet": "UN General Assembly, 79th session"},
    {"name": "Antigua and Barbuda", "position": "says", "who": "Gaston Browne", "role": "Prime Minister", "date": "2025-09",
     "quote": "we condemn the forced removal of people in Gaza from their homeland and the genocide that has occurred there",
     "source": "https://gadebate.un.org/sites/default/files/gastatements/80/ag_en.pdf", "outlet": "UN General Assembly, 80th session"},
    {"name": "Barbados", "position": "says", "who": "Mia Mottley", "role": "Prime Minister", "date": "2025-09",
     "quote": "the genocidal destruction taking place in Gaza",
     "source": "https://gadebate.un.org/sites/default/files/gastatements/80/bb_en.pdf", "outlet": "UN General Assembly, 80th session"},
    {"name": "Belize", "position": "says", "who": "Johnny Briceño", "role": "Prime Minister", "date": "2023-10-22",
     "quote": "committing genocide against the Palestinian people",
     "source": "https://lovefm.com/pm-briceno-dismisses-concerns-of-international-repercussions-for-israel-decision/",
     "outlet": "Love FM", "note": "Belize applied to intervene in South Africa v. Israel on 31 January 2025."},
    {"name": "Bosnia and Herzegovina", "position": "says", "who": "Željko Komšić",
     "role": "Chairman of the Presidency", "date": "2025-09-23",
     "quote": "genocide was committed in Bosnia and Herzegovina and, unfortunately, today we are witnessing its repetition in Gaza",
     "source": "https://www.euronews.ba/bosna-i-hercegovina/politika/36836/komsic-sa-beyanijem-prevencija-genocida-ne-smije-biti-politicko-pitanje",
     "outlet": "Euronews Bosnia",
     "note": "One of the three members of the collective presidency; he repeated it at the General Assembly the next day."},
    {"name": "Brazil", "position": "says", "who": "Luiz Inácio Lula da Silva", "role": "President", "date": "2026-09-22",
     "quote": "the genocide of women and children perpetrated by Netanyahu's government in Gaza",
     "source": UNGA81, "outlet": "Middle East Eye, on the 81st General Assembly",
     "note": "In June 2025 he called it “premeditated genocide”; Brazil intervened in South Africa v. Israel."},
    {"name": "Brunei", "position": "says", "who": "Sultan Hassanal Bolkiah", "role": "Head of state and government",
     "date": "2024-08", "quote": "the ongoing genocide and aggression in the Gaza Strip",
     "source": "https://www.mfa.gov.bn/Lists/Press%20Room/news.aspx?id=1129", "outlet": "Brunei Ministry of Foreign Affairs",
     "note": "In a joint statement with Malaysia's Prime Minister."},
    {"name": "China", "position": "says", "who": "State Council Information Office", "role": "Official government publication",
     "date": "2025-08-17", "summary": "The government's annual report on human rights in the United States accused Israel of "
     "committing genocide in Gaza with American complicity. China's response to the ICJ order of January 2024 had not used the word.",
     "source": "http://download.china.cn/en/doc/20250817.doc", "outlet": "State Council Information Office"},
    {"name": "Comoros", "position": "says", "who": "Azali Assoumani", "role": "President", "date": "2025-09-24",
     "quote": "amount[ing] to a genocide",
     "source": "https://gadebate.un.org/sites/default/files/gastatements/80/km_fr.pdf", "outlet": "UN General Assembly, 80th session",
     "note": "The Comoros intervened in South Africa v. Israel."},
    {"name": "Cuba", "position": "says", "who": "Miguel Díaz-Canel", "role": "President", "date": "2024-03-31",
     "quote": "Cuba demands that the genocide stop now.",
     "source": "https://www.timesofisrael.com/liveblog_entry/cuba-says-it-will-join-south-africas-icj-genocide-case-against-israel/",
     "outlet": "Times of Israel"},
    {"name": "Djibouti", "position": "says", "who": "Ismaïl Omar Guelleh", "role": "President", "date": "2023-11-11",
     "summary": "Told the Arab–Islamic summit in Riyadh that the Palestinians were being subjected to genocide.",
     "source": "https://www.spa.gov.sa/en/N1995662", "outlet": "Saudi Press Agency"},
    {"name": "Egypt", "position": "says", "who": "Abdel Fattah el-Sisi", "role": "President", "date": "2025-08-05",
     "quote": "systematic genocide",
     "source": "https://www.aljazeera.com/video/newsfeed/2025/8/5/president-of-egypt-accuses-israel-of-systematic", "outlet": "Al Jazeera"},
    {"name": "Ghana", "position": "says", "who": "Samuel Okudzeto Ablakwa", "role": "Foreign Minister", "date": "2025-09",
     "quote": "What is going on in Gaza is genocide",
     "source": "https://westafricaweekly.com/what-is-going-on-in-gaza-is-genocide-says-ghanas-foreign-minister/", "outlet": "West Africa Weekly",
     "note": "Said the government agreed with the UN Commission of Inquiry's finding."},
    {"name": "Guyana", "position": "says", "who": "Irfaan Ali", "role": "President", "date": "2024-04",
     "quote": "nothing short of genocide",
     "source": "https://www.thestkittsnevisobserver.com/nothing-short-of-genocide-says-guyanas-president-ali-as-he-calls-for-ceasefire-in-gaza/",
     "outlet": "St Kitts Nevis Observer"},
    {"name": "Indonesia", "position": "says", "who": "Sugiono", "role": "Foreign Minister", "date": "2025-08",
     "quote": "firmly rejects the genocide of the Palestinian people by Zionist Israel",
     "source": "https://rri.co.id/en/international/1744359/ri-reaffirms-unwavering-support-for-palestine-amid-ongoing-crisis", "outlet": "RRI"},
    {"name": "Iran", "position": "says", "who": "Masoud Pezeshkian", "role": "President", "date": "2025-09",
     "summary": "Accused Israel of committing genocide in Gaza in his address to the General Assembly.",
     "source": "https://gadebate.un.org/sites/default/files/gastatements/80/ir_en.pdf", "outlet": "UN General Assembly, 80th session"},
    {"name": "Iraq", "position": "says", "who": "Mohammed Shia' al-Sudani", "role": "Prime Minister", "date": "2024-05-08",
     "summary": "Said Israel's war in Gaza was tantamount to genocide.",
     "source": "https://www.middleeastmonitor.com/20240508-israel-onslaught-on-gaza-amounts-to-genocide-iraq-prime-minister-says/",
     "outlet": "Middle East Monitor"},
    {"name": "Ireland", "position": "says", "who": "Micheál Martin", "role": "Taoiseach", "date": "2025-09-26",
     "quote": "There cannot be business as usual in the face of genocide.",
     "source": "https://www.gov.ie/en/department-of-the-taoiseach/speeches/national-statement-by-taoiseach-miche%c3%a1l-martin-to-the-80th-session-of-the-united-nations-general-assembly-26th-september-2025/",
     "outlet": "Department of the Taoiseach",
     "note": "The Tánaiste and then Foreign Minister, Simon Harris, spoke of “the genocidal activity of the Netanyahu government” "
     "in May 2025, and the Dáil passed a motion on 7 November 2024 that “genocide is being perpetrated before our eyes”. "
     "Ireland intervened in South Africa v. Israel."},
    {"name": "Jordan", "position": "says", "who": "Ayman Safadi", "role": "Foreign Minister", "date": "2024-01-12",
     "summary": "Said Israel's actions in Gaza met the legal definition of genocide.",
     "source": "https://www.reuters.com/world/middle-east/jordan-says-failure-curb-israel-endangers-wider-region-2024-01-12/",
     "outlet": "Reuters"},
    {"name": "Kyrgyzstan", "position": "says", "who": "Edil Baisalov", "role": "Deputy Prime Minister", "date": "2024-03-18",
     "quote": "the madness and the genocide",
     "source": "https://tass.ru/mezhdunarodnaya-panorama/20270189", "outlet": "TASS"},
    {"name": "Lebanon", "position": "says", "who": "Najib Mikati", "role": "Prime Minister", "date": "2024-07-03",
     "quote": "the ongoing genocide against the Palestinians, namely in Gaza",
     "source": "https://www.middleeastmonitor.com/20240703-lebanon-calls-for-ending-israel-war-on-gaza/", "outlet": "Middle East Monitor",
     "note": "Mikati has since left office; the present government signed the joint statement of 15 August 2025."},
    {"name": "Libya", "position": "says", "who": "State of Libya", "role": "Declaration of intervention", "date": "2024-05-10",
     "summary": "Filed a declaration of intervention in South Africa v. Israel on the basis that Israel is committing genocide.",
     "source": "https://www.jurist.org/news/2024/05/libya-files-intervention-in-icj-genocide-case-against-israel/", "outlet": "JURIST"},
    {"name": "Malaysia", "position": "says", "who": "Anwar Ibrahim", "role": "Prime Minister", "date": "2024-05-19",
     "summary": "Called Israel's conduct in Gaza genocide and said the United States could not deny its complicity.",
     "source": "https://www.aljazeera.com/program/talk-to-al-jazeera/2024/5/19/malaysian-pm-cant-deny-us-complicity-in-gaza-genocide",
     "outlet": "Al Jazeera"},
    {"name": "Maldives", "position": "says", "who": "Mohamed Muizzu", "role": "President", "date": "2024-09-24",
     "quote": "the genocide by Israel in Gaza is a travesty of justice and the international system",
     "source": "https://www.aljazeera.com/news/2024/9/24/maldives-leader-says-israel-must-be-held-to-account-for-genocide-in-gaza",
     "outlet": "Al Jazeera", "note": "The Maldives intervened in South Africa v. Israel."},
    {"name": "Mauritania", "position": "says", "who": "Mohamed Ould Ghazouani", "role": "President", "date": "2023-11-11",
     "quote": "carrying out genocide in front of the world",
     "source": "https://english.ahram.org.eg/News/512037.aspx", "outlet": "Ahram Online"},
    {"name": "Mexico", "position": "says", "who": "Claudia Sheinbaum", "role": "President", "date": "2025-09-22",
     "summary": "Called Israel's assault on Gaza genocide as Mexico recognised the State of Palestine.",
     "source": "https://www.latimes.com/world-nation/story/2025-09-22/mexican-president-claudia-sheinbaum-calls-israeli-assault-on-gaza-a-genocide",
     "outlet": "Los Angeles Times", "note": "Mexico intervened in South Africa v. Israel."},
    {"name": "Namibia", "position": "says", "who": "Netumbo Nandi-Ndaitwah", "role": "President", "date": "2025-09-24",
     "quote": "indeed, a genocide is being committed against the Palestinian people",
     "source": "https://gadebate.un.org/sites/default/files/gastatements/80/na_en.pdf", "outlet": "UN General Assembly, 80th session",
     "note": "Her predecessor Hage Geingob called Israel's conduct “genocidal and gruesome” in January 2024. Namibia intervened in South Africa v. Israel."},
    {"name": "Nicaragua", "position": "says", "who": "Government of Nicaragua", "role": "Government", "date": "2024-10-11",
     "summary": "Broke diplomatic relations with Israel, calling its government “genocidal”.",
     "source": "https://www.reuters.com/world/americas/nicaragua-breaks-diplomatic-relations-with-israel-2024-10-11/", "outlet": "Reuters",
     "note": "Nicaragua applied to intervene in South Africa v. Israel in February 2024 and withdrew the application on 3 April 2025."},
    {"name": "Niger", "position": "says", "who": "Ali Lamine Zeine", "role": "Prime Minister", "date": "2025-09",
     "quote": "the Nigerien people unreservedly condemn the Israeli genocide in Gaza",
     "source": "https://www.lesahel.org/80e-session-de-lassemblee-generale-des-nations-unies-a-new-york-discours-de-m-ali-mahaman-lamine-zeine-premier-ministre-ministre-de-leconomie-et-des-finan/",
     "outlet": "Le Sahel"},
    {"name": "North Korea", "position": "says", "who": "Ministry of Foreign Affairs", "role": "Spokesperson", "date": "2023-10-26",
     "quote": "the U.S. is an accomplice who connived at and fostered Israel's genocide",
     "source": "https://www.reuters.com/world/north-korea-says-israel-bombed-gaza-hospital-calls-us-accomplice-2023-10-26/", "outlet": "Reuters"},
    {"name": "Oman", "position": "says", "who": "Ministry of Foreign Affairs", "role": "Government statement", "date": "2024-05",
     "summary": "Condemned the Israeli genocide of the Palestinian people.",
     "source": "https://www.middleeasteye.net/live-blog/live-blog-update/oman-condemns-israeli-genocide-palestinian-people", "outlet": "Middle East Eye"},
    {"name": "Pakistan", "position": "says", "who": "Shehbaz Sharif", "role": "Prime Minister", "date": "2025-09-26",
     "quote": "Israel's genocidal onslaught has unleashed unspeakable terror upon women and children",
     "source": "https://gadebate.un.org/sites/default/files/gastatements/80/pk_en.pdf", "outlet": "UN General Assembly, 80th session"},
    {"name": "Palestine", "position": "says", "who": "Mahmoud Abbas", "role": "President", "date": "2026-09-24",
     "quote": "genocidal war that has created an unprecedented humanitarian catastrophe",
     "source": "https://www.cbc.ca/news/world/mahmoud-abbas-united-nations-general-assembly-9.7356711", "outlet": "CBC News",
     "note": "Delivered by video after the United States refused him a visa. Palestine is a UN observer state and intervened in South Africa v. Israel."},
    {"name": "Qatar", "position": "says", "who": "Tamim bin Hamad Al Thani", "role": "Emir", "date": "2026-09-22",
     "quote": "genocide in the fullest sense of the word",
     "source": UNGA81, "outlet": "Middle East Eye, on the 81st General Assembly"},
    {"name": "Saint Lucia", "position": "says", "who": "Alva Baptiste", "role": "Minister for External Affairs", "date": "2025-09",
     "quote": "the undeniable genocide that is being committed against the people of Palestine, especially in Gaza",
     "source": "https://gadebate.un.org/sites/default/files/gastatements/80/lc_en.pdf", "outlet": "UN General Assembly, 80th session"},
    {"name": "Saint Vincent and the Grenadines", "position": "says", "who": "Office of the Prime Minister",
     "role": "Government statement", "date": "2024-01-11",
     "quote": "complicit in genocide before our very eyes",
     "source": "https://pmoffice.gov.vc/pmoffice/images/PDF/press_release/Media_Release_-_SVGs_Support_for_South_Africas_Case_against_Israel_at_the_ICJ_on_Genocide_in_Gaza.pdf",
     "outlet": "Office of the Prime Minister"},
    {"name": "Saudi Arabia", "position": "says", "who": "Ministry of Foreign Affairs", "role": "Government statement", "date": "2024-07",
     "quote": "continued genocidal massacres against the Palestinian people at the hands of the Israeli war machine",
     "source": "https://www.arabnews.com/node/2549146/saudi-arabia", "outlet": "Arab News"},
    {"name": "Senegal", "position": "says", "who": "Ousmane Sonko", "role": "Prime Minister", "date": "2024-06",
     "summary": "Said Palestine was being subjected to genocide with the complicity of the world's powers.",
     "source": "https://nan.media/en/senegal-palestine-is-being-subjected-to-genocide-with-the-complicity-of-all-the-worlds-powers/",
     "outlet": "NAN"},
    {"name": "Sierra Leone", "position": "says", "who": "Julius Maada Bio", "role": "President", "date": "2025-09-24",
     "quote": "A preventable genocide was not prevented.",
     "source": "https://gadebate.un.org/sites/default/files/gastatements/80/sl_en_0.pdf", "outlet": "UN General Assembly, 80th session"},
    {"name": "Slovenia", "position": "says", "who": "Nataša Pirc Musar", "role": "President", "date": "2025-05-21",
     "quote": "We are witnessing genocide",
     "source": "https://sloveniatimes.com/43569/president-calls-out-israel-for-genocide", "outlet": "Slovenia Times",
     "note": "Said to the European Parliament; she first named the West Bank and clarified that she meant Gaza."},
    {"name": "Somalia", "position": "says", "who": "Ministry of Foreign Affairs", "role": "Government statement", "date": "2024-01",
     "quote": "swift action to halt Gaza genocide by Israel",
     "source": "https://web.mfa.gov.so/somalia-applauds-icj-decision-urges-swift-action-to-halt-gaza-genocide-by-israel/",
     "outlet": "Somali Ministry of Foreign Affairs"},
    {"name": "Spain", "position": "says", "who": "Pedro Sánchez", "role": "Prime Minister", "date": "2026-09-23",
     "quote": "the genocide that Netanyahu is still perpetrating in Gaza",
     "source": "https://www.aa.com.tr/en/europe/spanish-prime-minister-calls-for-un-security-council-reform-condemns-gaza-genocide/4067176",
     "outlet": "Anadolu Agency, on the 81st General Assembly",
     "note": "In May 2025 he called Israel a “genocidal state”; the Council of Ministers adopted measures “to stop the genocide in Gaza” on 9 September 2025. Spain intervened in South Africa v. Israel."},
    {"name": "Timor-Leste", "position": "says", "who": "Bendito Freitas", "role": "Foreign Minister", "date": "2025-09",
     "quote": "the situation of famine and genocide",
     "source": "https://gadebate.un.org/sites/default/files/gastatements/80/tl_en.pdf", "outlet": "UN General Assembly, 80th session"},
    {"name": "Tunisia", "position": "says", "who": "Ministry of Foreign Affairs", "role": "Government statement", "date": "2024-05",
     "quote": "war of genocide",
     "source": "https://english.wafa.ps/Pages/Details/143881", "outlet": "WAFA"},
    {"name": "Turkey", "position": "says", "who": "Recep Tayyip Erdoğan", "role": "President", "date": "2026-09-22",
     "quote": "a genocidal mindset that is never satisfied with killing",
     "source": "https://www.aljazeera.com/news/2026/9/22/erdogan-slams-israels-genocidal-mindset-in-blistering-un-address",
     "outlet": "Al Jazeera, on the 81st General Assembly",
     "note": "He first called Israel's actions “amounting to genocide” in October 2023; Türkiye intervened in South Africa v. Israel."},
    {"name": "Yemen", "position": "says", "who": "Ministry of Foreign Affairs", "role": "Internationally recognised government",
     "date": "2023-10", "quote": "the war crimes and genocide",
     "source": "https://www.newarab.com/features/yemenis-put-aside-their-woes-unite-gaza-and-palestine", "outlet": "The New Arab"},
    {"name": "Zimbabwe", "position": "says", "who": "Christopher Mutsvangwa", "role": "Minister, speaking as ZANU–PF spokesman",
     "date": "2024-01-16", "quote": "genocidal practices and tendencies",
     "source": "https://www.heraldonline.co.zw/zanu-pf-hails-sa-suit-against-israeli-genocide/", "outlet": "The Herald",
     "note": "The weakest entry in this group: a serving minister, but speaking for the ruling party rather than the government."},
    {"name": "Sahrawi Republic", "position": "says", "who": "Brahim Ghali", "role": "President", "date": "2025-10-12",
     "quote": "perpetrators of crimes against humanity and genocide, such as the occupying Zionist entity",
     "source": "https://www.spsrasd.info/en/2025/10/13/12311.html", "outlet": "Sahara Press Service",
     "note": "Not a UN member state."},
    {"name": "Syria", "position": "says", "who": "Bashar al-Assad", "role": "President (until December 2024)", "date": "2024-11-11",
     "quote": "massacres, genocide and ethnic cleansing",
     "source": "https://archive.sana.sy/en/?p=341467", "outlet": "SANA",
     "note": "The Assad government fell in December 2024; the present government signed the joint statement of 15 August 2025."},

    # -------------------------------------------------------------- reversed
    {"name": "Chile", "position": "reversed", "who": "Gabriel Boric", "role": "President (until March 2026)", "date": "2024-09-25",
     "quote": "the genocide that Israel is carrying out in Palestine",
     "source": "https://www.infobae.com/america/america-latina/2024/09/25/gabriel-boric-me-rebelo-ante-quienes-pretenden-que-elijamos-entre-el-terrorismo-de-hamas-y-el-genocidio-de-israel/",
     "outlet": "Infobae",
     "now": "President José Antonio Kast has not repeated it, returned Chile's ambassador to Israel in August 2026 and "
     "appointed a self-declared Zionist, Gabriel Zaliasnik, as ambassador. Chile's intervention in South Africa v. Israel has not been withdrawn.",
     "now_source": "https://www.algemeiner.com/2026/08/04/chile-honduras-restore-ambassadors-to-israel-after-nearly-two-years-of-diplomatic-strains-over-gaza-war/"},
    {"name": "Colombia", "position": "reversed", "who": "Gustavo Petro", "role": "President (until August 2026)", "date": "2024-05-02",
     "summary": "Broke diplomatic relations with Israel over the conduct in Gaza and intervened in South Africa v. Israel on 5 April 2024.",
     "source": "https://www.icj-cij.org/case/192", "outlet": "International Court of Justice",
     "now": "President Abelardo de la Espriella withdrew Colombia's intervention on 18 September 2026 and is restoring relations with Israel.",
     "now_source": "https://www.un.org/unispal/document/icj-press-release-22sep26/"},
    {"name": "Bolivia", "position": "reversed", "who": "Luis Arce", "role": "President (until November 2025)", "date": "2024-02-21",
     "quote": "the truth about the genocide that is being committed against the brave Palestinian people",
     "source": "https://www.aljazeera.com/news/2024/2/21/colombia-bolivia-back-brazils-lula-in-israel-row-over-gaza-war-comments",
     "outlet": "Al Jazeera",
     "now": "President Rodrigo Paz restored relations with Israel in December 2025 and left the Hague Group in March 2026. "
     "Bolivia's intervention in South Africa v. Israel has not been withdrawn.",
     "now_source": "https://www.timesofisrael.com/israel-and-bolivia-renew-diplomatic-ties-after-two-years-of-rupture-over-gaza-war/"},
    {"name": "Honduras", "position": "reversed", "who": "Xiomara Castro", "role": "President (until January 2026)", "date": "2024-09-25",
     "quote": "an end to the genocide in Gaza",
     "source": "https://www.france24.com/es/medio-oriente/20240926-en-la-onu-los-l%C3%ADderes-alertan-sobre-el-peligro-de-la-escalada-del-conflicto-en-l%C3%ADbano",
     "outlet": "France 24",
     "now": "President Nasry Asfura visited Jerusalem as president-elect, left the Hague Group in March 2026 and returned Honduras's ambassador to Israel in August 2026.",
     "now_source": "https://www.algemeiner.com/2026/08/04/chile-honduras-restore-ambassadors-to-israel-after-nearly-two-years-of-diplomatic-strains-over-gaza-war/"},
    {"name": "Venezuela", "position": "reversed", "who": "Nicolás Maduro", "role": "President (until January 2026)", "date": "2023-10",
     "summary": "Condemned Israel's actions as genocide; his foreign minister Yván Gil spoke of “the genocide that his country is implementing on the proud Palestinian people”.",
     "source": "https://www.france24.com/es/medio-oriente/20231117-venezuela-arremete-contra-el-presidente-de-israel-por-cuestionar-su-postura-sobre-la-guerra-en-gaza",
     "outlet": "France 24",
     "now": "The acting government of Delcy Rodríguez agreed in August 2026 to resume relations with Israel and announced its withdrawal from the Rome Statute.",
     "now_source": "https://venezuelanvoices.org/2026/08/12/delcy-rodriguez-restores-relations-with-israel/"},

    # ---------------------------------------------------------------- defers
    {"name": "Australia", "position": "defers", "who": "Penny Wong", "role": "Foreign Minister", "date": "2025",
     "quote": "questions relating to genocide are matters where we respect the independence of international courts and tribunals",
     "source": "https://www.foreignminister.gov.au/minister/penny-wong/transcript/radio-interview-triple-j-hack-dave-marchese",
     "outlet": "Australian Minister for Foreign Affairs"},
    {"name": "Austria", "position": "defers", "who": "Beate Meinl-Reisinger", "role": "Foreign Minister", "date": "2025-07",
     "quote": "one should be very careful with the term 'genocide' and it will ultimately be the [ICJ] that has to judge it",
     "source": "https://euobserver.com/eu-and-the-world/ar997fdd48", "outlet": "EUobserver"},
    {"name": "Belgium", "position": "defers", "who": "Bart De Wever", "role": "Prime Minister", "date": "2025",
     "quote": "something for the International Court of Justice to determine",
     "source": "https://www.aljazeera.com/news/2025/12/23/belgium-joins-south-africas-genocide-case-against-israel-at-icj", "outlet": "Al Jazeera",
     "note": "The Foreign Minister, Maxime Prévot, said his personal opinion was that “this is very close to genocide”. Belgium intervened in South Africa v. Israel in December 2025."},
    {"name": "Canada", "position": "defers", "who": "Anita Anand", "role": "Foreign Minister", "date": "2025-09-17",
     "summary": "Noted that the matter is before the International Court of Justice; the UN ambassador, David Lametti, said all the evidence would need to be assessed first.",
     "source": "https://www.ipolitics.ca/2025/09/17/anand-condemns-israeli-military-offensive-in-gaza-but-stops-short-of-labelling-it-a-genocide/",
     "outlet": "iPolitics"},
    {"name": "Denmark", "position": "defers", "who": "Lars Løkke Rasmussen", "role": "Foreign Minister", "date": "2025-09",
     "summary": "Declined to call it genocide after the Commission of Inquiry's report, saying it was a matter for the courts.",
     "source": "https://danishnews.cphpost.dk/article/c5c5b635-6b44-4193-b6c0-9dd1069b00b4", "outlet": "The Copenhagen Post"},
    {"name": "Finland", "position": "defers", "who": "Elina Valtonen", "role": "Foreign Minister", "date": "2025-05",
     "summary": "Conceded in an interview that the conduct could hardly be anything other than genocide, but said the government would leave the final judgment to the ICJ.",
     "source": "https://yle.fi/a/74-20163319", "outlet": "Yle"},
    {"name": "France", "position": "defers", "who": "Jean-Noël Barrot", "role": "Foreign Minister", "date": "2025-07",
     "quote": "has no position to take on the legal description of the facts",
     "source": "https://franceintheus.org/spip.php?article11722", "outlet": "Embassy of France in the United States",
     "note": "In January 2024 his predecessor, Stéphane Séjourné, said accusing Israel of genocide was “to cross a moral threshold”."},
    {"name": "Iceland", "position": "defers", "who": "Þorgerður Katrín Gunnarsdóttir", "role": "Foreign Minister", "date": "2025-09-16",
     "quote": "this bears all the hallmarks of genocide",
     "source": "https://nyr.ruv.is/english/2025-09-16-fm-decision-on-joining-action-against-israel-to-be-made-next-month-453622", "outlet": "RÚV",
     "note": "She added that “it is for the International Court of Justice to decide this”. Iceland intervened in South Africa v. Israel in March 2026."},
    {"name": "Japan", "position": "defers", "who": "Takeshi Iwaya", "role": "Foreign Minister (until October 2025)", "date": "2025-09",
     "summary": "Said whether it is genocide must be determined on a detailed verification of the facts and in accordance with international law.",
     "source": "https://www.mofa.go.jp/press/kaiken/kaikenwe_000001_00197.html", "outlet": "Ministry of Foreign Affairs of Japan"},
    {"name": "Luxembourg", "position": "defers", "who": "Xavier Bettel", "role": "Foreign Minister", "date": "2024-01",
     "summary": "Declined to back South Africa's case, saying Luxembourg would remain neutral and await the Court's decision.",
     "source": "https://www.luxtimes.lu/luxembourg/bettel-refuses-to-back-genocide-case-against-israel-claims-neutrality/7296793.html",
     "outlet": "Luxembourg Times"},
    {"name": "Netherlands", "position": "defers", "who": "David van Weel", "role": "Foreign Minister", "date": "2025-09-18",
     "summary": "Said the Netherlands would not follow the Commission of Inquiry's finding and would await the ICJ.",
     "source": "https://nltimes.nl/2025/09/18/dutch-government-wont-label-gaza-war-genocide-un-report", "outlet": "NL Times",
     "note": "The Netherlands intervened in South Africa v. Israel in March 2026."},
    {"name": "New Zealand", "position": "defers", "who": "Winston Peters", "role": "Foreign Minister", "date": "2025-09",
     "quote": "interested in what the international courts might say, and that's what we would wait for",
     "source": "https://www.rnz.co.nz/news/political/573334/nz-govt-will-not-respond-on-latest-accusation-of-genocide-in-gaza", "outlet": "RNZ"},
    {"name": "Norway", "position": "defers", "who": "Espen Barth Eide", "role": "Foreign Minister", "date": "2024-09-02",
     "quote": "leave it to the court to assess whether the accusation of genocide is correct",
     "source": "https://www.utrop.no/nyheter/verden/358554/", "outlet": "Utrop"},
    {"name": "Singapore", "position": "defers", "who": "Vivian Balakrishnan", "role": "Foreign Minister", "date": "2025-09-22",
     "summary": "Noted the Commission of Inquiry's finding and called the ICJ “the appropriate forum to adjudicate such grave concerns”.",
     "source": "https://www.mfa.gov.sg/Newsroom/Press-Statements-Transcripts-and-Photos/2025/09/Ministerial-Statements-by-Minister-and-SMS-on-the-Situation-in-the-Middle-East-22-September-2025",
     "outlet": "Singapore Ministry of Foreign Affairs"},
    {"name": "Sweden", "position": "defers", "who": "Maria Malmer Stenergard", "role": "Foreign Minister", "date": "2025-09",
     "quote": "await the assessments from an international court before we establish that it is a matter of genocide",
     "source": "https://www.svt.se/nyheter/utrikes/forskargrupp-anklagar-israel-for-folkmord-i-gaza", "outlet": "SVT"},
    {"name": "United Kingdom", "position": "defers", "who": "Ed Miliband", "role": "Foreign Secretary", "date": "2026-09-08",
     "quote": "final determinations made by competent courts before the British Government reach a conclusion",
     "source": "https://hansard.parliament.uk/Commons/2026-09-08/debates/B9E48476-ADE4-4D56-8EA8-F76BBFF188E8/IsraelAndPalestine", "outlet": "Hansard, House of Commons",
     "note": "The Prime Minister, Andy Burnham, said in July 2026 that the question was for the international courts. "
     "The previous government's Foreign Secretary, David Lammy, wrote in 2025 that the conduct did not meet the criteria."},

    # --------------------------------------------------------------- unclear
    {"name": "Holy See", "position": "unclear", "who": "Pope Leo XIV", "role": "Head of state", "date": "2025-07",
     "quote": "Officially, the Holy See does not believe that we can make any declaration at this time",
     "source": "https://edition.cnn.com/2025/09/18/europe/pope-leo-trump-interview-ai-intl", "outlet": "CNN",
     "note": "He added that “more and more people are raising the issue”. Not a UN member state."},
    {"name": "Malta", "position": "unclear", "who": "Robert Abela", "role": "Prime Minister", "date": "2024-01",
     "quote": "I will leave it up to people to arrive at that conclusion on whether this is genocide",
     "source": "https://timesofmalta.com/article/watch-pm-stops-short-defining-israel-assault-gaza-genocide.1078794", "outlet": "Times of Malta"},
    {"name": "Russia", "position": "unclear", "who": "Sergey Lavrov", "role": "Foreign Minister", "date": "2025-10",
     "summary": "Said Russia would “wait and see” on South Africa's case and later noted that others use the word, without saying whether Russia does.",
     "source": "https://mid.ru/en/foreign_policy/news/2052617/", "outlet": "Russian Ministry of Foreign Affairs"},
    {"name": "Belarus", "position": "unclear", "who": "Alexander Lukashenko", "role": "President", "date": "2026-06-16",
     "summary": "Called the war a “Holocaust” and said Gaza had been “wiped off the face of the earth”, without using the word genocide.",
     "source": "https://www.ynetnews.com/article/b16xj00c11zx", "outlet": "Ynet"},
    {"name": "Uruguay", "position": "unclear", "who": "Yamandú Orsi", "role": "President", "date": "2025-06",
     "summary": "Said a resolution of the governing coalition condemning “ethnic cleansing and genocide” was a party's declaration and that the government was something else.",
     "source": "https://ladiaria.com.uy/politica/articulo/2025/6/orsi-dijo-que-la-resolucion-del-fa-sobre-gaza-es-la-declaracion-de-una-fuerza-politica-y-afirmo-que-el-gobierno-es-otra-cosa/",
     "outlet": "la diaria", "note": "The Vice-President, Carolina Cosse, said in October 2025 that it is genocide."},

    # --------------------------------------------------------------- rejects
    {"name": "Israel", "position": "rejects", "who": "Benjamin Netanyahu", "role": "Prime Minister", "date": "2026-09-24",
     "quote": "the biggest lie of the century",
     "source": "https://time.com/article/2026/09/24/netanyahu-dismisses-gaza-genocide-allegations-as-dozens-of-u-n-delegates-walk-out/",
     "outlet": "TIME, on the 81st General Assembly"},
    {"name": "United States", "position": "rejects", "who": "United States of America", "role": "Declaration of intervention",
     "date": "2026-03-12", "quote": "the allegations of “genocide” against Israel are false",
     "source": "https://www.icj-cij.org/sites/default/files/case-related/192/192-20260312-int-02-00-en.pdf", "outlet": "International Court of Justice"},
    {"name": "Germany", "position": "rejects", "who": "Friedrich Merz", "role": "Chancellor", "date": "2025-09-18",
     "summary": "Said he did not regard Israel's conduct as proportionate but did not regard it as genocide.",
     "source": "https://www.reuters.com/world/europe/merz-germany-still-decide-whether-back-sanctions-israel-2025-09-18/", "outlet": "Reuters"},
    {"name": "Italy", "position": "rejects", "who": "Antonio Tajani", "role": "Foreign Minister", "date": "2024-01-11",
     "quote": "genocide is something else",
     "source": "https://www.ansa.it/english/news/politics/2024/01/11/israel-has-hit-civilians-in-gaza-but-no-genocide-tajani_05247bb7-3385-42c9-a907-565bdba33c12.html",
     "outlet": "ANSA"},
    {"name": "Paraguay", "position": "rejects", "who": "Ministry of Foreign Affairs", "role": "Government statement", "date": "2024-01-10",
     "summary": "Rejected the accusations of genocide brought against Israel at the ICJ, and later intervened in the case.",
     "source": "https://www.ip.gov.py/ip/2024/01/10/paraguay-rejects-accusations-presented-against-israel-at-the-international-court-of-justice/",
     "outlet": "IP Paraguay"},
    {"name": "Poland", "position": "rejects", "who": "Radosław Sikorski", "role": "Foreign Minister", "date": "2025-09-30",
     "summary": "Called the civilian toll a terrible tragedy but said it did not in his view meet the definition of genocide.",
     "source": "https://www.polskieradio.pl/395/7785/artykul/3586746,fm-sikorski-calls-gaza-a-terrible-tragedy-stresses-careful-use-of-%E2%80%9Cgenocide",
     "outlet": "Polskie Radio"},
    {"name": "Portugal", "position": "rejects", "who": "Paulo Rangel", "role": "Foreign Minister", "date": "2024-05-13",
     "summary": "Said it would be “very unfair” to say Israel intends to eliminate the Palestinian people.",
     "source": "https://expresso.pt/politica/2024-05-13-paulo-rangel-recusa-que-israel-esteja-a-praticar-um-genocidio-em-gaza-mas-diz-que-catastrofe-humanitaria-exige-condenacao-a2dede0d",
     "outlet": "Expresso"},
    {"name": "Greece", "position": "rejects", "who": "Kyriakos Mitsotakis", "role": "Prime Minister", "date": "2025-09-17",
     "summary": "Said a major humanitarian disaster is unfolding but that he considers the term genocide “heavy”.",
     "source": "https://www.news247.gr/politiki/mitsotakis-gia-gaza-varis-o-oros-genoktonia/", "outlet": "News247"},
    {"name": "Costa Rica", "position": "rejects", "who": "Manuel Tovar", "role": "Foreign Minister", "date": "2026-07",
     "summary": "Said the government did not consider Israel's actions in Gaza to constitute genocide.",
     "source": "https://www.nacion.com/politica/manuel-tovar-niega-que-acciones-de-israel-en-gaza/4FEAUTIRBJCALJH4MB4KMQ233Y/story/",
     "outlet": "La Nación"},
    {"name": "Hungary", "position": "rejects", "who": "Government of Hungary", "role": "Declaration of intervention", "date": "2026-03-12",
     "summary": "Filed at the ICJ for a narrow reading of the Convention, arguing that civilian casualties and destruction do not in themselves show genocidal intent.",
     "source": "https://www.icj-cij.org/node/206230", "outlet": "International Court of Justice",
     "note": "Filed by the Orbán government a month before it lost office. The government of Péter Magyar has not withdrawn it or stated a view of its own."},
    {"name": "Fiji", "position": "rejects", "who": "Government of Fiji", "role": "Declaration of intervention", "date": "2026-03-12",
     "summary": "Filed at the ICJ in March 2026 alongside the United States and Hungary, in support of Israel's reading of the Convention.",
     "source": "https://www.icj-cij.org/node/206230", "outlet": "International Court of Justice"},
    {"name": "Czech Republic", "position": "rejects", "who": "Jan Lipavský", "role": "Foreign Minister (until December 2025)", "date": "2025-09-18",
     "summary": "Rejected the Commission of Inquiry's finding of genocide as partly “unfounded” and “beyond the pale”.",
     "source": "https://www.expats.cz/czech-news/article/czech-news-in-brief-for-september-18-2025-thursday-top-headlines", "outlet": "Expats.cz",
     "note": "The Babiš government, in office since December 2025, has not stated a view but has blocked EU sanctions on Israeli ministers."},
]

# Signatories of the joint statement with no statement of their own in the
# list above are placed in the joint group.
_OWN = {p["name"] for p in POSITIONS}
for _name in JOINT_2025_SIGNATORIES:
    if _name not in _OWN:
        POSITIONS.append(dict(JOINT_2025, name=_name, position="joint"))

LABELS = {
    "says": "Has called it genocide",
    "joint": "Signed a joint statement calling it genocide",
    "reversed": "Said it under a previous government; the present one has reversed course",
    "defers": "Says it is for a court to decide",
    "unclear": "Has not taken a clear position",
    "rejects": "Rejects or disputes it",
    "none": "No statement on the record",
}
